services:
  - type: web
    name: hat-telegram-mini-app
    env: node
    plan: free
    buildCommand: npm install && npm rebuild sqlite3
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: PERSISTENT_DIR
        value: /opt/render/project/src/backend/persistent
